# 旅遊行程
title = "Osaka Day Trip Itinerary"

# 行程步驟
[[steps]]
time = "08:52"
location = "飯店"
transport = "62公車"
station = "北浜二丁目〔大阪シティバス〕"
direction = "東"
destination = "天神橋(往吉車庫前［営業所內］方面)"

[[steps]]
time = "9:13"
location = "大阪城大手前站"
transport = "步行"
station = "大手門"
activity = "進入大阪城公園"

[[steps]]
time = ""
location = "大阪城公園"
transport = "步行"
station = "大阪城禦座船乗船處"
activity = "搭乘禦座船"

[[steps]]
time = ""
location = "大阪城公園"
transport = "步行"
station = "天守閣"

[[steps]]
time = ""
location = "大阪城公園"
transport = "步行"
station = "大手門"
activity = "離開大阪城公園"

[[steps]]
time = "12:02 [6分班距]"
location = "穀町四丁目車站"
transport = "地鐵"
station = "T23"
line = "紫-穀町線"
direction = "北"
destination = "[2]東梅田/都島 大日方面"

[[steps]]
time = "12:08"
location = "東梅田站"
transport = "地鐵"
station = "T20"
line = "紫-穀町線"
direction = "北"
exit = "1號出口方向/直到無障礙上坡"
activity = "進入Whity梅田地下商店街 (Northmall)"

[[steps]]
time = ""
location = "Whity梅田地下商店街站"
transport = "步行"
station = ""
line = ""
direction = "北"
exit = "案內所指示牌右前方通道 (NORTHMALL)"
activity = "進入Whity梅田地下商店街 (NORTHMALL 1)"

[[steps]]
time = ""
location = "5-6橘樓梯通道前"
transport = "步行"
exit = "H30 出口"
activity = "PUCHISHAN MALL通道前右轉離開"

[[steps]]
time = "12:15"
location = "HEP FIVE百貨"
transport = "手扶梯進入百貨"
activity = "7F 午餐 + 搭乘摩天輪"

[[steps]]
time = ""
location = "Whity梅田地下商店街"
transport = "步行"
station = "H28/H30 入口"
activity = "進入Whity地下街"

[[steps]]
time = "14:00"
location = "5-68通道樓梯前"
transport = "步行"
direction = "西"
destination = "不要進入NORTHMALL 1 通道/走 阪急電車方向"

[[steps]]
time = "14:08"
location = "梅田站"
transport = "地鐵"
station = "M16"
line = "紅-禦堂筋線"
direction = "南"
destination = "[1]なんば/天王寺 長居/なかもず方向 (所有方向都可以搭，優先搭１號車廂)"

[[steps]]
time = "14:13"
location = "本町站"
transport = "地鐵"
station = "M18"
line = "紅-禦堂筋線"
activity = "[南]轉乘至(綠-中央線)"

[[steps]]
time = "14:15"
location = "本町站"
transport = "地鐵"
station = "C16"
line = "綠-中央線"
direction = "西"
destination = "弁天町/大阪港/夢洲方面"
activity = "手扶梯進入地下二樓中央線"

[[steps]]
time = "14:26"
location = "大阪港"
transport = "地鐵"
station = "C11"
line = "綠-中央線"
exit = "1號出口"
activity = "往海遊館/天保山客船ターミナル"

[[steps]]
time = ""
location = "天保山"
transport = "觀光船"
activity = "搭帆船型觀光船 聖瑪麗亞號"

[[steps]]
time = ""
location = "天保山"
transport = "步行"
activity = "搭天保山大摩天輪"

[[steps]]
time = "17:30"
location = "大阪港"
transport = "地鐵"
station = "C11"
line = "綠-中央線"
direction = "西"
destination = "[1]本町/長田/生駒/學研奈良登美ヶ丘方面 (優先搭６號車廂)"

[[steps]]
time = "17:41"
location = "堺筋本町"
transport = "地鐵"
station = "C17"
line = "綠-中央線"
activity = "轉乘至(棕-堺筋線)"

[[steps]]
time = "17:44"
location = "堺筋本町"
transport = "地鐵"
station = "K16"
line = "棕-堺筋線"
direction = "南"
destination = "[1]日本橋/動物園前/天下茶屋方面 (優先搭１號車廂)"

[[steps]]
time = "17:49"
location = "恵美須町"
transport = "地鐵"
station = "K18"
line = "棕-堺筋線"
exit = "3號出口"
activity = "往 通天閣/恵美須町交差點南東/新世界"

[[steps]]
time = "17:52"
location = "通天閣"
transport = "步行"

[[steps]]
time = "18:34"
location = "恵美須町"
transport = "地鐵"
station = "K18"
line = "棕-堺筋線"
direction = "北"
destination = "[2]天神橋筋六丁目方面/北千里・高槻市方面"

[[steps]]
time = "18:37"
location = "日本橋"
transport = "地鐵"
station = "K17"
line = "棕-堺筋線"
destination = "3號出口或4號出口 - 地下街 (道頓堀)"
activity = "2號出口或5號出口 - 馬路 (道頓堀)"


[[steps]]
time = "20:29"
location = "心斎橋"
transport = "地鐵"
station = "M19"
line = "紅-禦堂筋線"
direction = "北"
destination = "[2]梅田/新大阪/箕面萱野方面 (所有方向皆可 優先搭１０號車廂)"

[[steps]]
time = "20:33"
location = "澱屋橋"
transport = "地鐵"
station = "M17"
line = "紅-禦堂筋線"
activity = "2號出口/通道 京阪電車のりば走"

[[steps]]
time = "21:00關門"
location = "北浜"
transport = "京阪電車聯絡道"
exit = "26號出口(京阪電車)"
activity = "離開"

[[steps]]
time = ""
location = "飯店"
transport = "步行"
